### ISSUE TITLE
Crash on Singleplayer load

### ISSUE THREAD

**Issue by superpowers04** [Gamepiaynmo/CustomModel#6] opened 2019-09-05 03:03 UTC
[Whenever I try to load into single player I get this ](https://paste.ee/p/66gNp)
I have tried multiple versions of fabric, autoconfig, fabric api, and mod menu with no luck
[(When compiling I get this)](https://paste.ee/p/SO6nH), Also I am using the Alex example for my model on my player

**Comment by Gamepiaynmo** [comment] 2019-09-09 11:14
It is caused by java version I think. Will be fixed in next update.

**Closed as completed** 2019-09-11 07:43 UTC
Labels: bug
